version: "3.8"

services:
  backend:
    image: node:18
    container_name: todo_backend
    working_dir: /app
    volumes:
      - ./back-end:/app
      - todo_db_data:/app/todo_data   # SQLite DB will persist here
    ports:
      - "5000:5000"
    env_file:
      - ./back-end/.env
    command:
      - sh
      - -c
      - |
        npm install
        node index.js

  frontend:
    image: node:18
    container_name: todo_frontend
    working_dir: /app
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev -- --host

volumes:
  todo_db_data:
