version: "3.8"

services:
  backend:
    build:
      context: ./back-end
    container_name: todo_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
    # optional: persist SQLite db
    # volumes:
    #   - sqlite_data:/app/data

  frontend:
    build:
      context: ./front-end
    container_name: todo_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}

# Uncomment if you want persistent database
# volumes:
#   sqlite_data:
