version: "3.8"

services:
  backend:
    image: node:18
    container_name: todo_backend
    working_dir: /usr/src/app
    volumes:
      - ./back-end:/usr/src/app
    ports:
      - "5000:5000"
    command:
      - sh
      - -c
      - |
        npm install
        node index.js

  frontend:
    image: node:18
    container_name: todo_frontend
    working_dir: /usr/src/app
    volumes:
      - ./front-end:/usr/src/app
    ports:
      - "3000:3000"
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev -- --host
