version: "3.8"

services:
  backend:
    image: node:18
    container_name: todo_backend
    working_dir: ./app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
    command:
      - sh
      - -c
      - |
        cd back-end
        npm install
        node index.js

  frontend:
    image: node:18
    container_name: todo_frontend
    working_dir: ./app
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
    command:
      - sh
      - -c
      - |
        cd front-end
        npm install
        npm run dev -- --port $FRONTEND_PORT --host
